import React, { useState, useEffect, useRef } from 'react';
import { Play, Pause, RotateCcw, AlertOctagon, CheckCircle2, ShieldAlert, Sparkles, Volume2, VolumeX } from 'lucide-react';
import { monitoringService } from '../../services/api';

export default function AIVideoPlayer({ pathData, onVideoComplete }) {
  const [isPlaying, setIsPlaying] = useState(false);
  const [progress, setProgress] = useState(0);
  const [currentSlideIndex, setCurrentSlideIndex] = useState(0);
  const [telemetryAlert, setTelemetryAlert] = useState('');
  const [sessionStatus, setSessionStatus] = useState('in_progress');
  const [isMuted, setIsMuted] = useState(false);

  const intervalRef = useRef(null);

  // Dynamic slides generated by AI based on knowledge gaps & course path
  const slides = [
    {
      title: `Overview: ${pathData?.course_title || 'Course Fundamentals'}`,
      subtitle: `Assessed Tier: ${pathData?.assessed_level || 'Beginner'}`,
      bullets: [
        `Custom objective: ${pathData?.objective || 'Focus on foundational comprehension'}`,
        `Addressing knowledge gap: ${pathData?.knowledge_gaps?.[0] || 'Core Syntax & Principles'}`,
        'AI Monitoring is actively tracking session focus and progression.'
      ],
      bg: 'from-slate-900 via-indigo-950 to-slate-900'
    },
    {
      title: `Deep Dive: ${pathData?.knowledge_gaps?.[0] || 'Key Topic Masterclass'}`,
      subtitle: 'Targeted Instructional Demonstration',
      bullets: [
        'Detailed breakdown of concepts missed during the pre-assessment quiz.',
        'Step-by-step logic execution and memory allocation walkthrough.',
        'Practical edge-case mitigation rules.'
      ],
      bg: 'from-slate-900 via-blue-950 to-slate-900'
    },
    {
      title: `Secondary Topic: ${pathData?.knowledge_gaps?.[1] || 'Practical Applications'}`,
      subtitle: 'Synthesis & Best Practices',
      bullets: [
        'Connecting theoretical principles to production architecture.',
        'Performance optimization tips to prepare for post-assessment.',
        'Final review of essential formulas and procedures.'
      ],
      bg: 'from-slate-900 via-purple-950 to-slate-900'
    }
  ];

  // AI Video monitoring: detect tab switching / window blur
  useEffect(() => {
    const handleVisibilityChange = () => {
      if (document.hidden && isPlaying) {
        setIsPlaying(false);
        setTelemetryAlert('AI Telemetry Alert: Focus lost! Tab switch detected.');
        monitoringService.sendTelemetry(1, 'focus_lost', progress, 'User switched tabs during video playback');
      }
    };
    document.addEventListener('visibilitychange', handleVisibilityChange);
    return () => document.removeEventListener('visibilitychange', handleVisibilityChange);
  }, [isPlaying, progress]);

  // Video playback timer loop
  useEffect(() => {
    if (isPlaying) {
      intervalRef.current = setInterval(() => {
        setProgress((prev) => {
          const next = prev + 2;
          // Calculate slide index
          if (next >= 66) setCurrentSlideIndex(2);
          else if (next >= 33) setCurrentSlideIndex(1);
          else setCurrentSlideIndex(0);

          // Periodically update telemetry
          if (next % 10 === 0) {
            monitoringService.sendTelemetry(1, 'progress_update', next);
          }

          if (next >= 100) {
            clearInterval(intervalRef.current);
            setIsPlaying(false);
            setSessionStatus('completed');
            monitoringService.sendTelemetry(1, 'completed', 100);
            if (onVideoComplete) onVideoComplete();
            return 100;
          }
          return next;
        });
      }, 500);
    } else {
      clearInterval(intervalRef.current);
    }
    return () => clearInterval(intervalRef.current);
  }, [isPlaying, onVideoComplete]);

  const togglePlay = () => {
    setIsPlaying(!isPlaying);
    setTelemetryAlert('');
  };

  const handleSeekAttempt = () => {
    // Detect forward seeking violation
    setTelemetryAlert('AI Anti-Cheat Alert: Fast-forward seek disabled. Complete content to satisfy learning monitoring.');
    monitoringService.sendTelemetry(1, 'seek_skip', progress, 'Forward seek attempted');
  };

  const currentSlide = slides[currentSlideIndex] || slides[0];

  return (
    <div className="bg-slate-900 border border-slate-700 rounded-2xl overflow-hidden shadow-2xl space-y-0">
      {/* Video Viewport / Canvas */}
      <div className={`h-80 bg-gradient-to-br ${currentSlide.bg} relative flex flex-col justify-between p-8 text-white transition-all duration-700 select-none`}>
        {/* Top Overlay Badge */}
        <div className="flex items-center justify-between z-10">
          <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-[11px] font-bold bg-blue-500/20 text-blue-300 border border-blue-400/30 backdrop-blur-md">
            <Sparkles className="w-3.5 h-3.5 text-blue-400 animate-spin" /> AI Generated Instructional Video
          </span>

          <div className="flex items-center gap-2">
            <span className={`text-[10px] uppercase font-bold px-2.5 py-1 rounded-md border backdrop-blur-md ${
              sessionStatus === 'completed'
                ? 'bg-emerald-950/80 text-emerald-400 border-emerald-500/50'
                : sessionStatus === 'incomplete'
                ? 'bg-rose-950/80 text-rose-400 border-rose-500/50'
                : 'bg-amber-950/80 text-amber-400 border-amber-500/50'
            }`}>
              Monitoring Status: {sessionStatus.replace('_', ' ').toUpperCase()}
            </span>
          </div>
        </div>

        {/* Slide Content Display */}
        <div className="z-10 my-auto space-y-3">
          <span className="text-xs text-blue-400 font-mono tracking-wider uppercase font-semibold">
            {currentSlide.subtitle}
          </span>
          <h3 className="text-2xl font-extrabold tracking-tight text-white leading-tight">
            {currentSlide.title}
          </h3>
          <ul className="space-y-1.5 pt-1">
            {currentSlide.bullets.map((b, i) => (
              <li key={i} className="text-xs text-slate-300 flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-blue-400 shrink-0" /> {b}
              </li>
            ))}
          </ul>
        </div>

        {/* Telemetry Warning Banner inside Video */}
        {telemetryAlert && (
          <div className="absolute bottom-16 left-6 right-6 z-20 bg-rose-950/90 border border-rose-500/50 text-rose-200 text-xs p-3 rounded-lg flex items-center gap-2 backdrop-blur-md animate-bounce">
            <AlertOctagon className="w-4 h-4 text-rose-400 shrink-0" />
            <span>{telemetryAlert}</span>
          </div>
        )}

        {/* Video Progress Bar */}
        <div className="w-full bg-slate-800/80 h-2 rounded-full overflow-hidden relative cursor-pointer" onClick={handleSeekAttempt}>
          <div
            className="bg-gradient-to-r from-blue-500 to-indigo-400 h-full transition-all duration-300 relative"
            style={{ width: `${progress}%` }}
          />
        </div>
      </div>

      {/* Control Bar */}
      <div className="bg-slate-850 p-4 border-t border-slate-800 flex items-center justify-between px-6 text-xs text-slate-300">
        <div className="flex items-center gap-4">
          <button
            onClick={togglePlay}
            className="w-10 h-10 rounded-full bg-blue-600 hover:bg-blue-500 text-white flex items-center justify-center transition-all shadow-lg shadow-blue-600/30"
          >
            {isPlaying ? <Pause className="w-5 h-5" /> : <Play className="w-5 h-5 ml-0.5" />}
          </button>

          <button onClick={() => setIsMuted(!isMuted)} className="text-slate-400 hover:text-white">
            {isMuted ? <VolumeX className="w-4 h-4" /> : <Volume2 className="w-4 h-4" />}
          </button>

          <span className="font-mono text-slate-400">
            {Math.floor((progress / 100) * 180)}s / 180s ({progress.toFixed(0)}%)
          </span>
        </div>

        <div className="flex items-center gap-2 text-slate-400 text-[11px]">
          <ShieldAlert className="w-4 h-4 text-blue-400" />
          <span>AI Telemetry Active (Anti-cheat & seek tracking enabled)</span>
        </div>
      </div>
    </div>
  );
}
